### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by wirehack7** [prikhi/lightdm-mini-greeter#13]
I'm getting that on Kali Linux:

```src/callbacks.c: In function ‘handle_password’:
src/callbacks.c:55:9: error: too many arguments to function ‘lightdm_greeter_respond’
         lightdm_greeter_respond(app->greeter, password_text, NULL);
         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/lightdm-gobject-1/lightdm.h:14:0,
                 from src/callbacks.c:3:
/usr/include/lightdm-gobject-1/lightdm/greeter.h:136:6: note: declared here
 void lightdm_greeter_respond (LightDMGreeter *greeter, const gchar *response);
      ^~~~~~~~~~~~~~~~~~~~~~~
Makefile:557: recipe for target 'src/lightdm_mini_greeter-callbacks.o' failed
make[1]: *** [src/lightdm_mini_greeter-callbacks.o] Error 1
make[1]: Leaving directory '/root/i3wm/lightdm-mini-greeter'
Makefile:381: recipe for target 'all' failed
make: *** [all] Error 2
```

Is either my system broken or the source?

**Comment by prikhi** [comment]
It seems the Kali Linux has an older LightDM, the latest version takes 3 arguments:

http://bazaar.launchpad.net/~lightdm-team/lightdm/trunk/view/head:/liblightdm-gobject/greeter.c#L1554

I'd have to look into if LightDM has a macro with the version number, then conditionally call the function with either 2 or 3 arguments depending on the version number.

What version of LightDM do you have installed?

**Comment by wirehack7** [comment]
lightdm 1.18.3

If I have to build lightdm from source, I say sorry. Then I have no interest in that project. I dont want to break depencies of my distro with not using the version of the package mirrors.

**Comment by prikhi** [comment]
Nah, I wouldn't require you to build/install a different version of lightdm. I'll take a look & see what I can do.

**Comment by prikhi** [comment]
Should be fixed now, will make a new release soon.

**Comment by prikhi** [comment]
And the readme now includes instructions for build .deb packages using debhelper.
