### ISSUE TITLE
Crashing after update to 0.3.1

### ISSUE THREAD

**Issue by ironman820** [prikhi/lightdm-mini-greeter#15]
I upgraded to the latest last night on an Arch install. Lightdm crashes running mini-greeter. All I see is the screen blink like it's starting the greeter and then it drops back to a cursor for a split second before systemd restarts lightdm. In case you need it, I'm running x86_64 on an Intel Core i5-3320M with an Intel i915 GPU (Dell Latitude E6230 laptop). I'm attaching a coredump (had to zip the lz4 to submit to GitHub).

[coredump.zip](https://github.com/prikhi/lightdm-mini-greeter/files/1667834/coredump.zip)

**Comment by prikhi** [comment]
Hmm, can you post your config? Did you merge your current config with the `.pacnew` file?

**Comment by prikhi** [comment]
And can you also check the logs in `/var/log/lightdm`?

**Comment by ironman820** [comment]
I apologize, I did a manual merge between my config and the `.pacnew` file. It looks like I missed one of the updated lines. I just overwrote my config with the `.pacnew` and set my username and it appears to be working fine now.

Sorry to waste your time with such a noob editing mistake.

**Comment by prikhi** [comment]
No problem, this was a rough release due to the new config options. In future releases I'll make sure old configurations still work correctly.
