### ISSUE TITLE
Configs without background-image set cause silent failure

### ISSUE THREAD

**Issue by F13** [prikhi/lightdm-mini-greeter#17]
With the addition of the "background-image" option, the greeter will fail to start if this option is not included. This is really only an issue IMO because previously working configs now cause a broken boot process. In my case, entries in /var/log/lightdm/lightdm.log indicate the greeter failed (with no more information), and /var/log/lightdm/seat0-greeter.log is empty.

This seems like it could be pretty confusing to troubleshoot. I wouldn't have found it if not for pacman dropping the .pacnew file for me to diff against.

Personally, I would expect background-image to be set to null if not found.

**Comment by prikhi** [comment]
Yeah sorry for the inconvenience, I'll be sure to make sure old configs work with new releases in the future. 

Are you running v0.3.0 or v0.3.1? I thought I had fixed this in the latest patch release but will investigate again if you are having issues with this on v0.3.1.

**Comment by F13** [comment]
I'm using the AUR package which (as far as I can tell) pulls directly from github. The package version reported is 0.3.1-1. If there's a more reliable way to check the version, let me know.

**Comment by prikhi** [comment]
Nah that's the best way. I maintain the AUR package so it should always be up to date.

I've pushed a fix in 113f4122cb0585130427c9c920afb80699292293, will release a new version soon.
