### ISSUE TITLE
User Customization

### ISSUE THREAD

**Issue by mehalter** [prikhi/lightdm-mini-greeter#18]
What about the ability to do user customizations like specifying the colors or background image in an optional config file in the home directory (`/home/$user/.config/`) of the user indicated in the main config.

I do color changing via scripts and would love to be able to easily change the colors of the greeter without the need of superuser privileges.

**Comment by prikhi** [comment]
I documented how to do this with a symlink that points to your `$HOME` directory - the `lightdm` user just needs to be able to read the file.

See: https://github.com/prikhi/lightdm-mini-greeter#config-file-in-home
