### ISSUE TITLE
Text colour option for "Password:" and such text

### ISSUE THREAD

**Issue by parnmatt** [prikhi/lightdm-mini-greeter#20]
Unless I am mistaken, but surely the default text colour option should style the `password-label-text`, and the incorrect password.

None of the style options change it for me; is this a bug? or is it a feaure yet to be added?

**Comment by rrothermund** [comment]
Having the same issue. Were you able to figure this out?

**Comment by golimpio** [comment]
I was having the same issue on Manjaro, so I've made a small change that fixed the issue for me. Follow the diff code, in case you're willing to install it from source:

```
diff --git a/src/ui.c b/src/ui.c
index 0a61115..2334301 100644
--- a/src/ui.c
+++ b/src/ui.c
@@ -228,12 +228,12 @@ static void attach_config_colors_to_screen(Config *config)
     int css_string_length = asprintf(&css,
         "* {\n"
             "font: %s %s;\n"
+            "color: %s;\n"
         "}\n"
         "GtkLabel {\n"
-            "color: %s;\n"
             "font-weight: bold;\n"
         "}\n"
-        "GtkLabel#error {\n"
+        "#error {\n"
             "color: %s;\n"
         "}\n"
         "#background {\n"
```

**Comment by golimpio** [comment]
I also had an issue with the error message not being displayed in the correct color, the patch above fix it as well.

**Comment by arawde** [comment]
Confirming that this is still broken (will add more specific version information in future)

**Comment by prikhi** [comment]
Sorry for the bouts of inactivity, this should be fixed now. Had to change `GtkLabel` to simply `label`. Will cut a new release for it soon.
