### ISSUE TITLE
Fallback options when omitted in the config file

### ISSUE THREAD

**Issue by mnacamura** [prikhi/lightdm-mini-greeter#22]
Many thanks to create this nice greeter.

It would be great if one can omit to explicitly describe some options in `/etc/lightdm/lightdm-mini-greeter.conf` and in such case default options are used as a fallback. For this users can keep a simpler configuration file.
Sorry if I misunderstand the behavior of loading the config file.

**Comment by prikhi** [comment]
Hi, thanks for the feedback!

Going forward, I'm making sure that any new options will fallback to a default if they're not in the config file, but I haven't gone backwards to make sure that this happens for all the previous/existing options.

It's a good idea though & perhaps eventually you will be able to simple have `user = myuser` in the config file if you want all the other options to be the default.

**Comment by prikhi** [comment]
Also, if you use Arch Linux, checkout `pacdiff` in the `pacman-contrib` package. It'll let you easily diff any new config files with your current version.

**Comment by prikhi** [comment]
Fixed by 69a1cb0 - now you only need to actually specify the `greeter.user` option, everything else will fallback to it's default value.
