### ISSUE TITLE
Linux Mint Package

### ISSUE THREAD

**Issue by dmcrider** [prikhi/lightdm-mini-greeter#24]
I've been trying for about 6 hours to get this set up on Linux Mint to no avail. Maybe I'm just missing something simple, but it would be a lot easier to just use `apt-get`. Is that a possibility for you? I'm a relatively novice Linux user and trying to figure this out manually is not fun - to say the least.

**Comment by prikhi** [comment]
I probably don't have the time to maintain a package in linux mints repositories, but now there's some documentation on how to properly build a package for debian/ubuntu based distributions:
https://github.com/prikhi/lightdm-mini-greeter#debian

Currently grabbing an ISO of Linux Mint to see if the same instructions apply.

**Comment by dmcrider** [comment]
I appreciate the effort. I'll keep trying as well.

**Comment by prikhi** [comment]
Just tested it out, seem to work fine with the latest changes. Here's the
commands I ran:

```sh
sudo apt-get install -yy git build-essential automake pkg-config fakeroot debhelper liblightdm-gobject-1-dev libgtk-3-dev
git clone https://github.com/prikhi/lightdm-mini-greeter
cd lightdm-mini-greeter
fakeroot dh binary
sudo dpkg -i ../lightdm-mini-greeter_0.3.2-1_amd64.deb
sudo nano /etc/lightdm/lightdm.conf.d/70-linuxmint.conf     # Add greeter-session=lightdm-mini-greeter
sudo nano /etc/lightdm/lightdm-mini-greeter.conf            # At the minimum, set the "user" option
sudo systemctl restart lightdm
```

Once lightdm restart, you should see the new greeter.

Gonna close this, but lemme know if you run into any more problems.

**Comment by prikhi** [comment]
I just release v0.3.3 & there's a deb file for linux mint on the [releases page](https://github.com/prikhi/lightdm-mini-greeter/releases)
