### ISSUE TITLE
Option for font size? 

### ISSUE THREAD

**Issue by sambles** [prikhi/lightdm-mini-greeter#3]
Hello, 

Is there an option to change the size of the font? It's more of a niggle for a HiDPI screen than a problem. 

I've Forked tried adding the option, but to be honest i'm a little lost. [Commit here](https://github.com/sambles/lightdm-mini-greeter/commit/4a844b56b4832f9aeb753141a3c55f89134e85cb)

I don't know much GTK, but guess that adding the option to the CSS should work? I see an option 'font‑size' in the docs [here](https://developer.gnome.org/gtk3/stable/chap-css-properties.html).

**Comment by prikhi** [comment]
I [commented on your commit](https://github.com/sambles/lightdm-mini-greeter/commit/4a844b56b4832f9aeb753141a3c55f89134e85cb#commitcomment-22634632).

If that gets this working, I'd accept a PR with the change.

**Comment by prikhi** [comment]
Fixed in #4
