### ISSUE TITLE
v0.3.3 ignores some settings on arch linux

### ISSUE THREAD

**Issue by Roshless** [prikhi/lightdm-mini-greeter#30]
[before](https://i.imgur.com/GHjT3Qq.png)
[after](https://i.imgur.com/pATnzgC.png)

Installed from AUR. No settings changed on either version. (setting background on 0.3.3 doesn't seem to change it anyway)

**Comment by prikhi** [comment]
Sorry! I thought I tested that out but I guess I didn't. 

Should be fixed in master & I'll make a new version soon.

**Comment by prikhi** [comment]
Also, the `password:` text was supposed to be bold this whole time. I can add an option to switch it though.

**Comment by prikhi** [comment]
Pushed the AUR update.

Also made a new `lightdm-mini-greeter-git` package.
