### ISSUE TITLE
Add keybinding to cycle through xsessions

### ISSUE THREAD

**Issue by prikhi** [prikhi/lightdm-mini-greeter#32]
Should (temporarily?) show the session we switch to.

How to enumerate available sessions & names?

**Comment by shreve** [comment]
Looking at [sddm](https://github.com/sddm/sddm/blob/develop/src/greeter/SessionModel.cpp#L115), it seems like they're just looking at all the sessions available in `/usr/share/xsessions`. You can parse the names out of those `.desktop` files.

I'm imagining a UI where you press the hotkey once to display the current val, then once visible, press again to cycle to the next available option.

**Comment by prikhi** [comment]
Fixed by 85e77d0685bd6cf13f3883da5b09d086f18979bc
