### ISSUE TITLE
Add more background image options

### ISSUE THREAD

**Issue by prikhi** [prikhi/lightdm-mini-greeter#33]
Add an options to:

*  specify the scaling type(none, fit, cover, etc.)
* change which monitors the background appears on

**Comment by frebib** [comment]
One feature that I cannot find in _any_ greeters/DMs is the ability to span a wallpaper over the entire root window of every display, synonymous to `feh --bg-fill --no-xinerama <file>`. It's a must for my setup

**Comment by tarkh** [comment]
Option for background sizing wold be very useful. Especially when you have multiple displays with different aspect ratio. Thank you!

**Comment by prikhi** [comment]
Fixed in #76
