### ISSUE TITLE
Background is not working

### ISSUE THREAD

**Issue by ahloiscreamo** [prikhi/lightdm-mini-greeter#34]
Hi
so i set the background  path in lightdm-mini-greeter config and it just loaded usual gray when i login.
weird thing is, when i output try in terminal it show the picture as-
![screenshot from 2019-01-13 22-09-43](https://user-images.githubusercontent.com/9318372/51086301-31301c00-1780-11e9-8720-0781188fc5cc.png)

terminal output-

~
❯ lightdm --test-mode -d
[+0.00s] DEBUG: Logging to /home/azrulFTW/.cache/lightdm/log/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.28.0, UID=1000 PID=11686
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-backup-logs.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-disable-guest.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-minimum-vt.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-session-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-user-authority-in-system-dir.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/50-xserver-command.conf
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /var/lib/flatpak/exports/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /home/azrulFTW/.local/share/flatpak/exports/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/xdg/lightdm/lightdm.conf.d/90-greeter-wrapper.conf
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf.d/40-io.elementary.greeter.conf
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Running in user mode
[+0.00s] DEBUG: Using Xephyr for X servers
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Registered seat module unity
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.01s] DEBUG: Monitoring logind for seats
[+0.01s] DEBUG: New seat added from logind: seat0
[+0.01s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.01s] DEBUG: Seat seat0: Starting
[+0.01s] DEBUG: Seat seat0: Creating greeter session
[+0.01s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+0.02s] DEBUG: Seat seat0: Creating display server of type x
[+0.02s] DEBUG: posix_spawn avoided (fd close requested) 
[+0.02s] DEBUG: Seat seat0: Starting local X display
[+0.02s] DEBUG: XServer 1: Logging to /home/azrulFTW/.cache/lightdm/log/x-1.log
[+0.02s] DEBUG: XServer 1: Writing X server authority to /home/azrulFTW/.cache/lightdm/run/root/:1
[+0.31s] DEBUG: XServer 1: Launching X Server
[+0.31s] DEBUG: Launching process 11691: /usr/bin/Xephyr :1 -seat seat0 -auth /home/azrulFTW/.cache/lightdm/run/root/:1 -nolisten tcp
[+0.31s] DEBUG: XServer 1: Waiting for ready signal from X server :1
[+0.31s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.31s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.31s] DEBUG: posix_spawn avoided (automatic reaping requested) (fd close requested) 
/bin/rm: cannot remove '/var/lib/lightdm-data/lightdm': Permission denied
[+3.63s] DEBUG: Got signal 10 from process 11691
[+3.63s] DEBUG: XServer 1: Got signal from X server :1
[+3.63s] DEBUG: XServer 1: Connecting to XServer :1
[+3.63s] DEBUG: Seat seat0: Display server ready, starting session authentication
[+3.63s] DEBUG: Session: Not setting XDG_VTNR
[+3.63s] DEBUG: Session pid=11708: Started with service 'lightdm-greeter', username 'azrulFTW'
[+3.65s] DEBUG: Session pid=11708: Authentication complete with return value 0: Success
[+3.65s] DEBUG: Seat seat0: Session authenticated, running command
[+3.65s] DEBUG: Session pid=11708: Not setting XDG_VTNR
[+3.65s] DEBUG: Session pid=11708: Running command /etc/lightdm/Xgreeter /usr/bin/lightdm-mini-greeter
[+3.65s] DEBUG: Creating shared data directory /var/lib/lightdm-data/azrulFTW
[+3.65s] DEBUG: Session pid=11708: Logging to /home/azrulFTW/.cache/lightdm/log/seat0-greeter.log
[+4.12s] DEBUG: Greeter connected version=1.28.0 api=1 resettable=false
[+4.12s] DEBUG: Greeter start authentication for azrulFTW
[+4.12s] DEBUG: Session: Not setting XDG_VTNR
[+4.12s] DEBUG: Session pid=11724: Started with service 'lightdm', username 'azrulFTW'
[+4.17s] DEBUG: Session pid=11724: Got 1 message(s) from PAM
[+4.17s] DEBUG: Prompt greeter with 1 message(s)
^C[+88.87s] DEBUG: Got signal 2 from process 0
[+88.87s] DEBUG: Caught Interrupt signal, shutting down
[+88.87s] DEBUG: Stopping display manager
[+88.87s] DEBUG: Seat seat0: Stopping
[+88.87s] DEBUG: Seat seat0: Stopping display server
[+88.87s] DEBUG: Sending signal 15 to process 11691
[+88.87s] DEBUG: Seat seat0: Stopping session
[+88.87s] DEBUG: Session pid=11708: Sending SIGTERM
[+88.87s] DEBUG: Seat seat0: Stopping session
[+88.87s] DEBUG: Session pid=11724: Sending SIGTERM
[+88.87s] DEBUG: Session pid=11708: Terminated with signal 2
[+88.87s] DEBUG: Seat seat0: Session stopped
[+88.87s] DEBUG: Session pid=11724: Terminated with signal 2
[+88.87s] DEBUG: Session: Failed during authentication
[+88.87s] DEBUG: Seat seat0: Session stopped
[+88.91s] DEBUG: Process 11691 exited with return value 0
[+88.91s] DEBUG: XServer 1: X server stopped
[+88.91s] DEBUG: XServer 1: Removing X server authority /home/azrulFTW/.cache/lightdm/run/root/:1
[+88.91s] DEBUG: Seat seat0: Display server stopped
[+88.91s] DEBUG: Seat seat0: Stopped
[+88.91s] DEBUG: Display manager stopped
[+88.91s] DEBUG: Stopping daemon
[+88.91s] DEBUG: Exiting with return value 0

~ 1m 29s
❯ 

Lightdm ver. 1.28.0
OS- fedora29

**Comment by prikhi** [comment]
Hmm, could you post the logs from /var/log/lightdm? Do you think it could be a permissions error? Maybe try copying the image to `/etc/lightdm/` and pointing the config value to that one?

**Comment by ahloiscreamo** [comment]
hay you were right!
permission problem, i copy the pic as your pointing and it work like flawless now.
Thanks a ton!,ill close this issue.

**Comment by shreve** [comment]
This would be nice to add to documentation. I figured I had a permission problem and tried a few lightdm-related directories until I found this issue and realized `/etc/lightdm` is the only one that works. It also can't be a symlink.
