### ISSUE TITLE
mini-greet misbehaving on laptop wakeup 

### ISSUE THREAD

**Issue by novel-notion** [prikhi/lightdm-mini-greeter#35]
When I first boot, mini greeter loads fine and looks great - works as intended. However, when I close my laptop lid and open it again everything looks a bit wonky. For some reason my gnome desktop image displays and the login window isn't even close to what it should be. I am using Awesome WM by default. See images below. Any thoughts?

![IMG_20190325_235942](https://user-images.githubusercontent.com/5490759/54970959-b68f3400-4f5a-11e9-8f6e-3218ea03c74c.jpg)
![IMG_20190326_000115](https://user-images.githubusercontent.com/5490759/54970962-ba22bb00-4f5a-11e9-80ce-bca1948952d8.jpg)

**Comment by prikhi** [comment]
Do you have some screen locker installed? That first image isn't mini-greeter

**Comment by novel-notion** [comment]
I just did some more digging into the commands being run on wakeup, and it looks like gnome-screensaver is being run, I didn't recognize it. Is there a way to run mini-greeter instead?

Feel free to close this issue as this isn't a problem relating directly to mini-greeter.
