### ISSUE TITLE
Changing the password input field width

### ISSUE THREAD

**Issue by hfel** [prikhi/lightdm-mini-greeter#52]
Hello!

It would be nice to have the ability to change the width of the password input field itself; currently, only changing the dimension of the space around it is possible. My password is quite long, but only about 5 1/2 dots are currently visible, after which the user gets no typing feedback from the screen at all.

**Comment by prikhi** [comment]
Got this sketched out, I'll push it soon. But it seems like we can only give GTK a hint of what the width should be, it does some calculation magic which seems to shrink the width a bit. E.g., a width of 30 characters ends up fitting only 23 characters, a width of 50 about 47, etc.

**Comment by prikhi** [comment]
Fixed by fa0a828f217931190fb13bedaee3a64603f9a844
