### ISSUE TITLE
can't login (password is wrong)

### ISSUE THREAD

**Issue by jujey** [prikhi/lightdm-mini-greeter#55]
this keeps happening to me every time i try to login using lightdm-mini-greeter i put my user password but it doesn't login, it just keeps saying that the password is wrong even though it's clearly not

(this also happens with lightdm-tiny-greeter)

**Comment by rban123** [comment]
you have to specify which user the greeter is authenticating for in your `lightdm-mini-greeter.conf`.
under the `[greeter]` section, make sure you set `user = yourusername`

**Comment by jujey** [comment]
> you have to specify which user the greeter is authenticating for in your `lightdm-mini-greeter.conf`.
> under the `[greeter]` section, make sure you set `user = yourusername`

i did set my user, 
![Screenshot from 2020-02-25 21-43-21](https://user-images.githubusercontent.com/58881699/75290240-e2283780-5817-11ea-82e3-448aab938aa9.png)
i set it to `user = jujey`
and after restarting i ser my password and i just doesn't work

**Comment by rban123** [comment]
You also have to specify a default Desktop Environment for lightdm in `lightdm.conf`, make sure you set `user-session=xfce`, replacing xfce with whichever desktop environment you want to use, you may need to uncomment this line, which should be around line 107 in `~/etc/lightdm/lightdm.conf`

**Comment by hippwn** [comment]
I had the very same issue and setting a `user-session` didn't help. What did is removing the _white space_ that I accidentally added at the end of my username before the newline.

I feel like the field should be stripped of any non-alphanumeric character. Hope it helps.

**Comment by prikhi** [comment]
@hippwn I made issue #59 to strip trailing whitespace from the user field. 

@jujey Can you see if there is a space at the end of your user line?

**Comment by mikkelrask** [comment]
Oh man... It hurts to find out that I also fell for the trailing white space. :/ Came here to see if there was any current issues, and sure enough...

**Comment by prikhi** [comment]
This was fixed in v0.5.0

**Comment by phdcybersec** [comment]
> Hi there, I wonder how should I move on? I am stuck at login due to this issue.  Do I need to reinstall Linux?

You can definitely open another TTY, log in, modify the file and reload your display manager.

**Comment by PSGrobet** [comment]
Had the same issue and setting the default desktop in lightdm.config fixed it. Thanks.
