### ISSUE TITLE
Keyboard issue ?

### ISSUE THREAD

**Issue by ISs25u** [prikhi/lightdm-mini-greeter#56]
Hi !

I'm trying to use the mini-greeter but I can't log in : when I enter my password nothing happens. I'm using an azerty/french keyboard, so I was wondering if it can be the cause of my problem.

**Comment by prikhi** [comment]
Hi, have you reviewed the [Configure](https://github.com/prikhi/lightdm-mini-greeter#configure) section of the README? Specifically, you currently have to set the `user` field of the greeter's config and possibly the `user-session` in lightdm's configuration.

**Comment by prikhi** [comment]
To clarify, when you say "when I enter my password nothing happens", do you mean when you type your password in no characters appear in the input, or when you hit enter to try to log in with it nothing happens?

**Comment by ISs25u** [comment]
Nothing happens when I hit enter. I can type my password but I can't see if I'm typing right because the characters are hidden.

**Comment by mamyn0va** [comment]
Same problem here with correct `user` and `user-session` fields.

**Comment by ISs25u** [comment]
Solved by editing `/etc/X11/xorg.conf.d/00-keymap.conf` : 
```
Section "InputClass"
  Identifier "system-keyboard"
  MatchIsKeyboard "on"
  Option  "XkbModel"    "pc105"
  Option  "XkbLayout"   "fr,us"
  Option  "XkbOptions"  "grp:caps_toggle,grp_led:caps"
EndSection
```

**Comment by prikhi** [comment]
> Solved

Sweet, I had no idea how to test this without buying a keyboard lol.
Would you be into making a PR adding a sub-section for this to the Configure section of the readme?
