### ISSUE TITLE
Unable to login: `pam_get_uid; no such user`, even though user is set in the config file

### ISSUE THREAD

**Issue by Wint3rmute** [prikhi/lightdm-mini-greeter#57]
Hi!

I'm using the AUR version,  I've checked both `lightdm-mini-greeter` and `lightdm-mini-greeter-git` packages, on two different Arch installs. Each time I try to login, I get this error message in the logs:

```
Mar 23 14:18:31 arch553ve systemd[1]: Started Light Display Manager.
Mar 23 14:18:33 arch553ve lightdm[11209]: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)
Mar 23 14:18:33 arch553ve lightdm[11221]: pam_tally2(lightdm:auth): pam_get_uid; no such user
Mar 23 14:18:40 arch553ve lightdm[11221]: pam_unix(lightdm:auth): check pass; user unknown
Mar 23 14:18:40 arch553ve lightdm[11221]: pam_unix(lightdm:auth): authentication failure; logname= uid=0 euid=0 tty=:0 ruser= rhost=
Mar 23 14:18:40 arch553ve lightdm[11221]: gkr-pam: error looking up user information
```

I'm sure this is a problem with the greeter, since I can login using the `lightdm-gtk-greeter`.

I have set the `user` variable in the greeter config and the `user-sesssion` variable in the lightdm config.
The greeter is reading the config (I can change the window colors and the background image), but
it looks like something is wrong with the username.

My lightdm version (output from pacman -Q) is
`lightdm 1:1.30.0-2`

**Comment by prikhi** [comment]
Can you make sure there's not a trailing space after your username in the config file?

**Comment by Wint3rmute** [comment]
Thank you for answering!

Indeed, after removing a trailing space, I can log in.

I've played around with `g_key_file_get_string`, the function used for getting the values from the config file. It only removes the whitespace from the begginning of the value ([exactly how the documentation says](https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html)).

I think that stripping the username from the extra whitespace during config parsing would prevent such accidents from happening. The usernames can't contain spaces anyway.

**Comment by prikhi** [comment]
Cool, I'll take out any trailing whitespace - made #59 to handle it.
