### ISSUE TITLE
User should be set to generic

### ISSUE THREAD

**Issue by gbc921** [prikhi/lightdm-mini-greeter#6]
Hi, at [this line](https://github.com/prikhi/lightdm-mini-greeter/blob/194bfdbfea9b7520f4b859fcb6b8b9d3c883a500/data/lightdm-mini-greeter.conf#L7) the user is set as your username.

I guess it would be better to have it as a generic one, indicating that this should be changed later.
Better yet would be the case where the script would change this name to the user logged in when compiling/installing the software.

What do you think?

Tks,

**Comment by prikhi** [comment]
Short on time at the moment, but seems fine to change it to `CHANGE_ME` or something. Maybe show or log a warning if it's set to the default value.

**Comment by prikhi** [comment]
Fixed by 62b699c
