### ISSUE TITLE
Symlink to configuration

### ISSUE THREAD

**Issue by tosti007** [prikhi/lightdm-mini-greeter#65]
Hey there! 

I have some of my system's configuration placed in a dotfiles repository. In order to safe lightdm-mini-greeter's configuration inside these dotfiles I will need to make a symlink from `/etc/lightdm/lightdm-mini-greeter.conf` to my own desired path. Doing so will result in lightdm-mini-greeter having no valid configuration to work with. 

How can I use a symlink for the configuration file or is this a feature that can be added to lightdm-mini-greeter?
Many thanks in advance!

**Comment by yylian** [comment]
I am also interested in this.

**Comment by Achileas** [comment]
Or Cant the configuration be inside a user home directory? Is it possible?

**Comment by prikhi** [comment]
This is possible, but you need to tweak permissions so that LightDM can read the destination of the symlink. I added some docs on this to the README in 83f2a2c81607e57245be9557945b49386e10d896.
