### ISSUE TITLE
Add Ability to Set Border Radius on Password Input

### ISSUE THREAD

**Issue by Barbarossa93** [prikhi/lightdm-mini-greeter#67]
Contrary to #63 , I was wondering if its possible to change/remove the border radius on the password entry border?

**Comment by prikhi** [comment]
Most likely, just gotta figure out if it's a GtkEntry function or a CSS thing. Gimme a day or two.

**Comment by prikhi** [comment]
Got this working, will add a `password-border-radius` field that you can use arbitrary CSS sizes with(`0`, `5px`, `2rem`, etc). & it took me a while, but through judicious usage of screenshots, I was able to figure out the correct default value to make the config backwards compatible...

For any future people that happen to be googling something like "GTK Entry Default Border Radius" - it's `0.341125em` :expressionless: 

Commit incoming, maybe tonight or tomorrow.

**Comment by prikhi** [comment]
Fixed in 10c27727959214ce8512a68ea5dbf0e8d211e104.
