### ISSUE TITLE
Ability to set password mask character

### ISSUE THREAD

**Issue by katacarbix** [prikhi/lightdm-mini-greeter#68]
Instead of the default large dots it would be nice to be able to set it to an asterisk or some other character using the same font settings for the labels.

**Comment by b-** [comment]
Leaving this here mostly for my own notes, as I’ll see what I can do here. (Can you tag yourself? @b- )

The method in question: https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-invisible-char

Likely place to put it: https://github.com/prikhi/lightdm-mini-greeter/blob/a9e56a580dcd6110a08d734546cb428eed0913fd/src/ui.c#L224

gonna go to sleep and see if I can hack it in the morning.

**Comment by prikhi** [comment]
The font for the "bullets" should be inherited by the `greeter-theme.font` setting.

I'll look into adding a config for the invisible char, but it seems like we'll need to be able to specify a character, no characters, or the default character.

**Comment by prikhi** [comment]
Mkay, I got it working but the code is kinda dirty at the moment. I attempt parsing twice, first as an int(where -1 means default, 0 means no characters) & then fall back to a string if int parsing fails(taking only the first character of the string). You can even change them emojis if that's your style:

![2021-02-11-011539_819x576_scrot](https://user-images.githubusercontent.com/1304102/107607240-a9d76000-6c06-11eb-9107-a34cc84fbb59.png)


If string/unicode parsing fails it falls back to the default.

I'll clean it up & push it tomorrow.

**Comment by prikhi** [comment]
Fixed by 1c23df18aed135ed0bb2703a61e3b20960bb2f79.

Gonna try & at least get the corner border radius in before cutting a new release.

**Comment by katacarbix** [comment]
I just tested it and it works great! Thanks so much for being so quick to add this!!
