### ISSUE TITLE
[Request] Center password entry

### ISSUE THREAD

**Issue by Barbarossa93** [prikhi/lightdm-mini-greeter#69]
Thanks so much for the password radius option! To me, it was a huge improvement visually. The only thing I'd like to see now is the password entry be centered within the box. Currently the only options are left and right.

**Comment by prikhi** [comment]
Ooo, you know I thought only left & right were possible because this documentations only mentions 0 & 1:

https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-alignment

But according to this, looks like we could set it to 0.5 to get it centered. I'll check it out.

**Comment by prikhi** [comment]
Fixed by 43e1807

> The only thing I'd like to see now is the password entry be centered within the box.

If your mini-greeter is 100% configured to how you like it, I'd love to see a pic of what you came up with :)
