### ISSUE TITLE
Add a fallback to a standard config in the case of errors in the config file

### ISSUE THREAD

**Issue by MarcusVH98** [prikhi/lightdm-mini-greeter#75]
Hi. I encountered a situation where I was missing a single hashtag before a hex-code in the config, which made the greeter hang on a black screen with a blinking cursor in the top left. I could not even get into tty (The tty flashed on screen briefly). I had to mount the drive and edit the config file from a live usb to fix it. Having a fallback like qtile has would be great for this situation.

PS. This is my first issue, so if I worded it weird or whatever, just let me know.

**Comment by prikhi** [comment]
Fixed by 69a1cb0
