### ISSUE TITLE
Invalid password issue

### ISSUE THREAD

**Issue by WahidIslamLinad** [prikhi/lightdm-mini-greeter#80]
Today I installed mini greeter from AUR but after setting up everything my password isn't working.. characters are being placed but invalid pass everytime. i didn't check keyboard layout settings cz mine is us layout (which is default i think)..
[Note: my password does include @ maybe issue with that? ;/ ]
wm: bspwm
distro: endeavour os (arch)
(running on vm)

**Comment by prikhi** [comment]
US layout should work fine - it's what I use & haven't done any overrides. You've set the `user` in the config file? Are you using the main package or the `-git` package? Does anything in `/var/log/lightdm/` help?

**Comment by WahidIslamLinad** [comment]
> US layout should work fine - it's what I use & haven't done any overrides. You've set the `user` in the config file? Are you using the main package or the `-git` package? Does anything in `/var/log/lightdm/` help?

Hello @prikhi .. thanks for your reply..I installed the the stable package not the git one..maybe it's causing error cause probably i didn't config user as i was just trying it out..I am really new to linux so couldn't check logs😅..is there any way to config the user now?
