### ISSUE TITLE
Core dump when startup

### ISSUE THREAD

**Issue by MizuyoruTW** [prikhi/lightdm-mini-greeter#81]
I had a new install  from AUR, after setting up, I restarted lightdm.service, but nothing happened except my cursor blinking on the top left.
`lightdm --test-mode` works perfectly.

The following are the core dump message from journal, if the other infomation is needed, please tell me, I will reply ASAP.

        Process 2674 (lightdm-mini-gr) of user 954 dumped core.

        Stack trace of thread 2674:
        #0  0x00007fd2c14b595b g_logv (libglib-2.0.so.0 + 0x5c95b)
        #1  0x00007fd2c14b5c30 g_log (libglib-2.0.so.0 + 0x5cc30)
        #2  0x00007fd2b43051c0 n/a (libfcitx-gclient.so.1 + 0x51c0)
        #3  0x00007fd2c1145a64 n/a (libgio-2.0.so.0 + 0xa0a64)
        #4  0x00007fd2c1145a99 n/a (libgio-2.0.so.0 + 0xa0a99)
        #5  0x00007fd2c14ad3e5 g_main_context_dispatch (libglib-2.0.so.0 + 0x543e5)
        #6  0x00007fd2c1501749 n/a (libglib-2.0.so.0 + 0xa8749)
        #7  0x00007fd2c14aca63 g_main_loop_run (libglib-2.0.so.0 + 0x53a63)
        #8  0x00007fd2c18b188f gtk_main (libgtk-3.so.0 + 0x1d388f)
        #9  0x000055b4f40f60d8 n/a (lightdm-mini-greeter + 0x30d8)
        #10 0x00007fd2c1295b25 __libc_start_main (libc.so.6 + 0x27b25)
        #11 0x000055b4f40f611e n/a (lightdm-mini-greeter + 0x311e)

        Stack trace of thread 2683:
        #0  0x00007fd2c1361b2f __poll (libc.so.6 + 0xf3b2f)
        #1  0x00007fd2c15016d9 n/a (libglib-2.0.so.0 + 0xa86d9)
        #2  0x00007fd2c14aca63 g_main_loop_run (libglib-2.0.so.0 + 0x53a63)
        #3  0x00007fd2c11a8268 n/a (libgio-2.0.so.0 + 0x103268)
        #4  0x00007fd2c14dbd11 n/a (libglib-2.0.so.0 + 0x82d11)
        #5  0x00007fd2c0781259 start_thread (libpthread.so.0 + 0x9259)
        #6  0x00007fd2c136c5e3 __clone (libc.so.6 + 0xfe5e3)

        Stack trace of thread 2681:
        #0  0x00007fd2c136718d syscall (libc.so.6 + 0xf918d)
        #1  0x00007fd2c14fbb3b g_cond_wait_until (libglib-2.0.so.0 + 0xa2b3b)
        #2  0x00007fd2c147c7c3 n/a (libglib-2.0.so.0 + 0x237c3)
        #3  0x00007fd2c14dea4b n/a (libglib-2.0.so.0 + 0x85a4b)
        #4  0x00007fd2c14dbd11 n/a (libglib-2.0.so.0 + 0x82d11)
        #5  0x00007fd2c0781259 start_thread (libpthread.so.0 + 0x9259)
        #6  0x00007fd2c136c5e3 __clone (libc.so.6 + 0xfe5e3)

        Stack trace of thread 2675:
        #0  0x00007fd2c078d8ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
        #1  0x00007fd2c0787270 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf270)
        #2  0x00007fd2bb3d38cc n/a (iris_dri.so + 0x1c88cc)
        #3  0x00007fd2bb3ccfa8 n/a (iris_dri.so + 0x1c1fa8)
        #4  0x00007fd2c0781259 start_thread (libpthread.so.0 + 0x9259)
        #5  0x00007fd2c136c5e3 __clone (libc.so.6 + 0xfe5e3)

        Stack trace of thread 2682:
        #0  0x00007fd2c136718d syscall (libc.so.6 + 0xf918d)
        #1  0x00007fd2c14fbb3b g_cond_wait_until (libglib-2.0.so.0 + 0xa2b3b)
        #2  0x00007fd2c147c7c3 n/a (libglib-2.0.so.0 + 0x237c3)
        #3  0x00007fd2c14dea4b n/a (libglib-2.0.so.0 + 0x85a4b)
        #4  0x00007fd2c14dbd11 n/a (libglib-2.0.so.0 + 0x82d11)
        #5  0x00007fd2c0781259 start_thread (libpthread.so.0 + 0x9259)
        #6  0x00007fd2c136c5e3 __clone (libc.so.6 + 0xfe5e3)

        Stack trace of thread 2680:
        #0  0x00007fd2c136718d syscall (libc.so.6 + 0xf918d)
        #1  0x00007fd2c14fbb3b g_cond_wait_until (libglib-2.0.so.0 + 0xa2b3b)
        #2  0x00007fd2c147c7c3 n/a (libglib-2.0.so.0 + 0x237c3)
        #3  0x00007fd2c14dea4b n/a (libglib-2.0.so.0 + 0x85a4b)
        #4  0x00007fd2c14dbd11 n/a (libglib-2.0.so.0 + 0x82d11)
        #5  0x00007fd2c0781259 start_thread (libpthread.so.0 + 0x9259)
        #6  0x00007fd2c136c5e3 __clone (libc.so.6 + 0xfe5e3)

        Stack trace of thread 2679:
        #0  0x00007fd2c1361b2f __poll (libc.so.6 + 0xf3b2f)
        #1  0x00007fd2c15016d9 n/a (libglib-2.0.so.0 + 0xa86d9)
        #2  0x00007fd2c14aabc1 g_main_context_iteration (libglib-2.0.so.0 + 0x51bc1)
        #3  0x00007fd2c14aac12 n/a (libglib-2.0.so.0 + 0x51c12)
        #4  0x00007fd2c14dbd11 n/a (libglib-2.0.so.0 + 0x82d11)
        #5  0x00007fd2c0781259 start_thread (libpthread.so.0 + 0x9259)
        #6  0x00007fd2c136c5e3 __clone (libc.so.6 + 0xfe5e3)

**Comment by prikhi** [comment]
Hmm, did you grab the normal aur package or the `-git` version?

Anything useful in `/var/log/lightdm`?

What changes did you make to the config?

**Comment by MizuyoruTW** [comment]
> Hmm, did you grab the normal aur package or the `-git` version?
> 
> Anything useful in `/var/log/lightdm`?
> 
> What changes did you make to the config?

Hi,
I am using normal ver., but I had tested the git ver. didn't work too.

I had checked the log in /ver/log/lightdm, I found there are some error in those logs:
`Could not run plymouth --ping: Failed to execute child process “plymouth” (No such file or directory)` in lightdm.log
`GLib-GIO-CRITICAL **: 22:10:17.418: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed` in seat0-greeter.log

I only changed the username in the config

**Comment by prikhi** [comment]
Do you have a `fcitx` package installed? I found a few issues like this:
https://unix.stackexchange.com/questions/490871/lubuntu-g-is-dbus-connection

Could you try uncommenting/setting this line in `lightdm.conf`:
```
[Seat:*]
session-wrapper=/etc/lightdm/Xsession
```

**Comment by MizuyoruTW** [comment]
> Do you have a `fcitx` package installed? I found a few issues like this: https://unix.stackexchange.com/questions/490871/lubuntu-g-is-dbus-connection
> 
> Could you try uncommenting/setting this line in `lightdm.conf`:
> 
> ```
> [Seat:*]
> session-wrapper=/etc/lightdm/Xsession
> ```
> 
> Not sure if that'll work, I have a feeling it'll only start dbus once you log in & not when the lightdm starts up.

Yes, I have `fcitx` installed, I had seen that site, but it seems I don't have `fcitx-module-dbus` installed.

The
```
[Seat:*]
session-wrapper=/etc/lightdm/Xsession
```
has already been uncommented by default, comment it didn't help.

**Comment by MizuyoruTW** [comment]
I uninstalled fctix, and installed fcitx5 instead. Surprisingly, the greeter works!
It looked like it had something wrong with fcitx.

Thank you for replying.
