### ISSUE TITLE
Readme: Example image broke

### ISSUE THREAD

**Issue by tadghh** [prikhi/lightdm-mini-greeter#90]
"Error Fetching Resource"
https://camo.githubusercontent.com/b9b74bb9b8fa7878d41a32e6e26d9b771988704f27f5a08173da0dbaf40bbd8a/687474703a2f2f627567732e736c656570616e61726368792e636f6d2f70726f6a656374732f6d696e692d677265657465722f7265706f7369746f72792f7265766973696f6e732f6d61737465722f656e7472792f73637265656e73686f742e706e67

**Comment by prikhi** [comment]
Thanks, fixed in https://github.com/prikhi/lightdm-mini-greeter/commit/ead7936993b4e9e067d73fa49dec7edfb46c73a8
